version: "3"
services:
  db:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=david
      - MYSQL_PASSWORD=david
      - MYSQL_DATABASE=db1
    volumes:
      - type: bind
        source: /c/temp/mysql/mysql8
        target: /var/lib/mysql/
    container_name: mysql8